## Operações com Arrays 
Podemos operar com diversos (ou todos) elementos de um array numa única operação. \
Suponha que tenhamos o array 0..9 e queremos somar 10 a todos os elementos do array. É possível fazer essa operação sem usar um laço? Em Python, sim!

In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(0,10)
arr1 + 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Se fizermos arr1 - 10 teremos o vetor original?

In [ ]:
arr1 - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

Vamos agora criar outro array (arr2), contendo os elementos 10..19. \
Assim como somamos um inteiro aos elementos de um array, podemos somar dois arrays. \
Vejamos o resultado de arr1 + arr2:

In [ ]:
arr2 = np.arange(10,20)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
arr1+arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

Para alterar um elemento do array, basta indicar o índice desse elemento. \
Ex: alterar o primeiro elemento de arr1, colocando 10 no lugar de 0.

In [ ]:
arr1[0] = 10
arr1

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

E se quisermos alterar todos os elementos do array, colocando 10 em todas as posições?

In [ ]:
arr1[:] =  10
arr1

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

Exercício 1 \
Altere os 5 primeiros elementos de arr1, colocando o valor 20.

In [ ]:
arr1[:5] = 20
arr1

array([20, 20, 20, 20, 20, 10, 10, 10, 10, 10])

Exercício 2 \
Altere os 3 últimos elementos de arr1, colocando o valor 30.

In [ ]:

arr1[7:] = 30
arr1

array([20, 20, 20, 20, 20, 10, 10, 30, 30, 30])

Vamos agora criar um novo array (arr3), utilizando os 5 primeiros elementos de arr2. 

In [ ]:
arr3 = arr2[:5]
arr3

array([10, 11, 12, 13, 14])

A seguir, vamos colocar 0 em todos os elementos de arr3 e observar o que acontece com arr2.

In [ ]:
arr3[:] = 0
arr2

#use o copy!!

array([ 0,  0,  0,  0,  0, 15, 16, 17, 18, 19])

O que aconteceu foi que arr3 não foi criado com novos valores. Este array "aponta" para os 5 primeiros valores de arr2. Assim, ao alterar os elementos de arr3, alteramos também os 5 primeiros elementos de arr2.

A função reshape do numpy permite mesclar dois arrays.

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr
result = arr.reshape(-1)
result

array([1, 2, 3, 4, 5, 6])

Apendando arrays

In [ ]:
arr4 = np.arange(0,10)
arr5 = np.arange(10,20)
print(arr4)
print(arr5)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [ ]:
arr6 = np.append(arr4,arr5)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Exercício 3 \
Escreva um programa que gere o seguinte array: [1, 2, 3, 4, 5]. Em seguida, leia 5 valores digitados pelo usuário e os apende no array inicial. Finalmente, print o array resultante.

In [ ]:
valores_inicio = np.arange(1,6)
valores_usuario = np.array([int(input()) for x in range(0,5)])
print(np.append(valores_inicio, valores_usuario))

[ 1  2  3  4  5  1  2  3 89  6]


Exercício 4 \
Crie um array de 20 elementos contendo valores entre 1 e 100. Em seguida, leia valores digitados pelo usuário até que o valor lido conste no array. Ao final, print o array e o último valor lido.

In [ ]:
rng = np.random.default_rng() # inicializa o gerador de números aleatórios
arr9 = rng.integers(low=1, high=101, size=20) # gera o vetor de números aleatórios 
while True:
    valor_lido = int(input())
    if valor_lido in arr9:
        break
print(arr9, valor_lido)

[10  1 77 48 58 44 53 52 41 69 58 90 13 53 95 50 45  8 66 45] 45
